<a href="https://colab.research.google.com/github/pedroc28/Comp_Quant/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
%%capture
!pip install qiskit qiskit-aer matplotlib numpy
import numpy as np
from qiskit.quantum_info import Statevector
import matplotlib.pyplot as plt

### 1. Introdução à Álgebra Linear na Computação Quântica

A computação quântica não é apenas sobre física; é, fundamentalmente, sobre o processamento de informação através de estados lineares. Para manipular um computador quântico com eficiência, precisamos dominar a linguagem da Álgebra Linear complexa.

Neste primeiro módulo, seguindo os fundamentos apresentados no curso e na referência clássica de **Nielsen & Chuang**, revisaremos:

*   **Notação de Dirac (Bra-Ket):** A linguagem padrão para descrever estados quânticos.
*   **Vetores e Espaços de Hilbert:** A estrutura matemática onde nossos qubits residem.
*   **Operadores Lineares:** Como as matrizes representam as portas lógicas que transformam a informação quântica.

> **Nota:** Trabalharemos extensivamente com números complexos. Certifique-se de estar familiarizado com a representação $a + bi$.


### 2. Notação de Dirac (Bra-Ket)

A notação de Dirac é a ferramenta padrão utilizada para representar e manipular estados em espaços vetoriais complexos ($\mathbb{C}^n$). Ela simplifica a representação geométrica e algébrica dos sistemas quânticos através de dois elementos fundamentais:

* **Ket $|\psi\rangle$:** Representa um **vetor coluna**. É o objeto matemático básico que define o estado quântico de um sistema (como um *qubit*).

$$|\psi\rangle = \begin{bmatrix} z_1 \\ z_2 \\ \vdots \\ z_n \end{bmatrix}$$

* **Bra $\langle\psi|$:** Representa um **vetor linha**. Ele pertence ao espaço dual e é obtido diretamente a partir do Ket correspondente através da operação de **transposta conjugada** (também chamada de adjunto ou *adjoint*, denotada pelo símbolo $\dagger$).

$$\langle\psi| = |\psi\rangle^\dagger = \begin{bmatrix} z_1^* & z_2^* & \dots & z_n^* \end{bmatrix}$$

> **Nota Matemática:** O símbolo $*$ indica o **conjugado complexo** de um número. Lembre-se que se um elemento do vetor for $z = a + bi$, seu conjugado complexo será $z^* = a - bi$ (invertendo o sinal da parte imaginária). A operação adjunta $|\psi\rangle^\dagger$ combina a transposição geométrica (linha vira coluna) com a conjugação complexa.

In [37]:
import numpy as np

# Definindo um Ket genérico (Vetor Coluna 2x1)
# No Python, utilizamos a letra 'j' fixada ao número para indicar a parte imaginária
ket_psi = np.array([[1 + 2j],
                    [3 - 4j]])

print("Vetor Coluna - Ket |𝜓>:")
print(ket_psi)

# Calculando o Bra correspondente através da Transposta Conjugada (Adjoint)
# .conj() altera o sinal da parte imaginária (a + bj -> a - bj)
# .T rotaciona a matriz de coluna para linha
bra_psi = ket_psi.conj().T

print("\nVetor Linha - Bra <𝜓|:")
print(bra_psi)

Vetor Coluna - Ket |𝜓>:
[[1.+2.j]
 [3.-4.j]]

Vetor Linha - Bra <𝜓|:
[[1.-2.j 3.+4.j]]


### 3. Produto Interno, Norma e Ortogonalidade

Agora que sabemos operar com Kets e Bras isolados, podemos combiná-los para extrair informações geométricas e probabilísticas fundamentais para os sistemas quânticos.

#### A. Produto Interno
O produto interno entre dois vetores $|\phi\rangle$ e $|\psi\rangle$ é indicado por $\langle\phi|\psi\rangle$ (um "Bra" encontrando um "Ket"). O resultado dessa operação é sempre um **número complexo**. Matricialmente, multiplicamos o vetor linha pelo vetor coluna:

$$\langle\phi|\psi\rangle = \begin{bmatrix} w_1^* & w_2^* & \dots & w_n^* \end{bmatrix} \begin{bmatrix} z_1 \\ z_2 \\ \vdots \\ z_n \end{bmatrix} = w_1^*z_1 + w_2^*z_2 + \dots + w_n^*z_n$$

#### B. Norma e Normalização
A **norma** (que associamos intuitivamente ao "comprimento" ou magnitude) de um vetor é calculada tirando a raiz quadrada do produto interno do vetor por ele mesmo:

$$\|\psi\| = \sqrt{\langle\psi|\psi\rangle}$$

> **Importância Quântica:** De acordo com os fundamentos quânticos, qualquer estado físico válido deve ser **normalizado**, o que significa que sua norma deve ser obrigatoriamente igual a 1 ($\|\psi\| = 1$). Isso garante a consistência estatística: a soma das probabilidades de todos os resultados possíveis após uma medição deve ser exatamente $100\%$.
>
> Se tivermos un vetor não normalizado, dividimos cada um de seus elementos pela sua respectiva norma para ajustá-lo:
> $$|\psi_{norm}\rangle = \frac{|\psi\rangle}{\|\psi\|}$$

#### C. Ortogonalidade
Dois estados quânticos são ditos **Ortogonais** se o produto interno entre eles for igual a zero

$$\langle\phi|\psi\rangle = 0$$

Geometricamente, isso significa que eles são perpendiculares no espaço complexo. Na computação quântica, estados ortogonais representam alternativas físicas perfeitamente distinguíveis (como os estados clássicos $0$ e $1$, ou os estados de superposição $|+\rangle$ e $|-\rangle$).

---
#### Laboratório Interativo de Vetores
Utilize o formulário interativo na célula de código abaixo para testar diferentes vetores. Você pode alterar os valores na barra lateral direita do Colab e rodar a célula novamente para recalcular automaticamente o Produto Interno, as Normas, a Ortogonalidade e a versão Normalizada dos seus vetores!

In [33]:
#@title Sandbox Interativo de Álgebra Linear quântica
import numpy as np

# --- ENTRADA DE DADOS VIA FORMULÁRIO (Altere os valores na direita) ---

#@markdown #### 🔹 Configuração do Vetor 1:  |𝜙⟩ = [w1, w2]^T
phi_w1_real = 1.0 #@param {type:"number"}
phi_w1_imag = 0.0 #@param {type:"number"}
phi_w2_real = 1.0 #@param {type:"number"}
phi_w2_imag = 0.0 #@param {type:"number"}

#@markdown #### 🔹 Configuração do Vetor 2:  |psi⟩ = [z1, z2]^T
psi_z1_real = 1.0 #@param {type:"number"}
psi_z1_imag = 0.0 #@param {type:"number"}
psi_z2_real = -1.0 #@param {type:"number"}
psi_z2_imag = 0.0 #@param {type:"number"}

# --- PROCESSAMENTO MATEMÁTICO ---

# 1. Construindo os Kets a partir dos dados do formulário
ket_phi = np.array([[complex(phi_w1_real, phi_w1_imag)],
                    [complex(phi_w2_real, phi_w2_imag)]])

ket_psi = np.array([[complex(psi_z1_real, psi_z1_imag)],
                    [complex(psi_z2_real, psi_z2_imag)]])

# 2. Calculando os Bras correspondentes (Transposta Conjugada)
bra_phi = ket_phi.conj().T
bra_psi = ket_psi.conj().T

# 3. Cálculo do Produto Interno <𝜙|psi⟩
prod_interno = np.dot(bra_phi, ket_psi)[0, 0]

# 4. Cálculo das Normas Originais
norma_phi = np.linalg.norm(ket_phi)
norma_psi = np.linalg.norm(ket_psi)

# 5. Normalização dos vetores
ket_phi_norm = ket_phi / norma_phi if norma_phi > 0 else ket_phi
ket_psi_norm = ket_psi / norma_psi if norma_psi > 0 else ket_psi


# --- EXIBIÇÃO DOS RESULTADOS FORMATADOS ---

print("-> VETORES INSERIDOS:")
print("Ket |𝜙⟩ original:\n", ket_phi)
print("\nKet |𝜓⟩ original:\n", ket_psi)

print("\n-> PRODUTO INTERNO E ORTOGONALIDADE:")
print(f"Produto Interno <𝜙|𝜓⟩ = {prod_interno}")

# Teste numérico de ortogonalidade considerando aproximações de ponto flutuante
if np.isclose(prod_interno, 0):
    print("RESULTADO: Os estados |𝜙⟩ e |𝜓⟩ são ORTOGONAIS! (Produto interno é 0)")
else:
    print("RESULTADO: Os estados NÃO são ortogonais.")

print("\n-> NORMAS E NORMALIZAÇÃO:")
print(f"Norma original de |𝜙⟩: {norma_phi:.4f} " + ("✅ (Válido)" if np.isclose(norma_phi, 1) else "❌ (Inválido quânticamente)"))
print(f"Norma original de |𝜓⟩: {norma_psi:.4f} " + ("✅ (Válido)" if np.isclose(norma_psi, 1) else "❌ (Inválido quânticamente)"))

print("\n--- Versões Normalizadas Prontas para Uso Quântico ---")
print("Ket |𝜙_norm⟩:\n", ket_phi_norm)
print(f"Nova norma de |𝜙_norm⟩: {np.linalg.norm(ket_phi_norm):.1f}")

print("\nKet |𝜓_norm⟩:\n", ket_psi_norm)
print(f"Nova norma de |𝜓_norm⟩: {np.linalg.norm(ket_psi_norm):.1f}")
print("="*60)

-> VETORES INSERIDOS:
Ket |𝜙⟩ original:
 [[1.+0.j]
 [1.+0.j]]

Ket |𝜓⟩ original:
 [[ 1.+0.j]
 [-1.+0.j]]

-> PRODUTO INTERNO E ORTOGONALIDADE:
Produto Interno <𝜙|𝜓⟩ = 0j
RESULTADO: Os estados |𝜙⟩ e |𝜓⟩ são ORTOGONAIS! (Produto interno é 0)

-> NORMAS E NORMALIZAÇÃO:
Norma original de |𝜙⟩: 1.4142 ❌ (Inválido quânticamente)
Norma original de |𝜓⟩: 1.4142 ❌ (Inválido quânticamente)

--- Versões Normalizadas Prontas para Uso Quântico ---
Ket |𝜙_norm⟩:
 [[0.70710678+0.j]
 [0.70710678+0.j]]
Nova norma de |𝜙_norm⟩: 1.0

Ket |𝜓_norm⟩:
 [[ 0.70710678+0.j]
 [-0.70710678+0.j]]
Nova norma de |𝜓_norm⟩: 1.0


In [34]:
import numpy as np

# 1. Definindo os estados da base computacional padrão: |0> e |1>
ket_0 = np.array([[1],
                  [0]])

ket_1 = np.array([[0],
                  [1]])

# Calculando o produto interno <0|1>
# Lembre-se que é preciso extrair o Bra de |0> (.conj().T) para multiplicar pelo Ket |1>
bra_0 = ket_0.conj().T
prod_interno_01 = np.dot(bra_0, ket_1)

print(f"Produto Interno <0|1>: {prod_interno_01[0,0]} -> Logo, são ortogonais!")

# 2. Exemplo de Normalização (Construindo o estado quântico |+> passo a passo)
# Começamos com um vetor não normalizado |w> = [1, 1]^T
ket_w = np.array([[1],
                  [1]])

# Calculando a norma utilizando a função linalg.norm do NumPy
norma_w = np.linalg.norm(ket_w)
print(f"\nNorma original do vetor |w>: {norma_w} -> Não é um estado válido ainda!")

# Normalizando o vetor (dividindo o Ket pela sua norma)
ket_w_normalizado = ket_w / norma_w
print("\nKet |w> normalizado de forma correta (Estado quântico |+>):")
print(ket_w_normalizado)

# Validação: checando se a nova norma é igual a 1
print(f"\nVerificação da nova norma: {np.linalg.norm(ket_w_normalizado)}")

# Definindo os estados quânticos |+> e |-> (Base de Hadamard)
# Ambos são construídos a partir da superposição de |0> e |1>
ket_plus = (1 / np.sqrt(2)) * np.array([[1],
                                        [1]])

ket_minus = (1 / np.sqrt(2)) * np.array([[1],
                                         [-1]])

# Exibindo os kets na tela
print("Estado |+>:")
print(ket_plus)
print("\nEstado |->:")
print(ket_minus)

Produto Interno <0|1>: 0 -> Logo, são ortogonais!

Norma original do vetor |w>: 1.4142135623730951 -> Não é um estado válido ainda!

Ket |w> normalizado de forma correta (Estado quântico |+>):
[[0.70710678]
 [0.70710678]]

Verificação da nova norma: 0.9999999999999999
Estado |+>:
[[0.70710678]
 [0.70710678]]

Estado |->:
[[ 0.70710678]
 [-0.70710678]]


### 4. Operadores Lineares e Representação Matricial

Na computação clássica, a informação é modificada por portas lógicas tradicionais (AND, OR, NOT). Na computação quântica, qualquer modificação em um *qubit* é feita por um **operador linear**, que pode ser representado computacionalmente como uma **matriz quadrada**.

Se temos um operador linear $A$ atuando sobre um estado $|\psi\rangle$, o novo estado quântico será um novo Ket $|\psi'\rangle$ resultante da multiplicação da matriz pelo vetor:

$$|\psi'\rangle = A |\psi\rangle$$

#### A. Matrizes de Pauli
As matrizes de Pauli são três das portas lógicas quânticas mais fundamentais para um único *qubit*. Elas mapeiam rotações e inversões de spin:

* **Porta $X$ (NOT quântico):** Inverte os componentes do vetor (transforma $|0\rangle$ em $|1\rangle$ e vice-versa).
$$X = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$$

* **Porta $Y$:** Aplica uma inversão de bit combinada com uma mudança de fase complexa.
$$Y = \begin{bmatrix} 0 & -i \\ i & 0 \end{bmatrix}$$

* **Porta $Z$:** Inverte a fase do estado $|1\rangle$, deixando o estado $|0\rangle$ inalterado.
$$Z = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}$$

#### B. Operadores Unitários
De acordo com o **Postulado 2**, a evolução de um sistema quântico fechado é descrita por operadores **unitários**. Uma matriz $U$ é dita unitária se a sua transposta conjugada ($U^\dagger$) for igual à sua própria inversa:

$$U^\dagger U = I$$

Onde $I$ é a matriz identidade.

> **Nota:** Geometricamente, as transformações unitárias atuam como rotações no espaço vetorial complexo. Elas possuem a propriedade crucial de **preservar o produto interno** e, consequentemente, a **norma** dos vetores. Isso significa que se começarmos com um estado quântico perfeitamente normalizado (norma = 1), qualquer porta quântica válida (unitária) aplicada a ele garantirá que o estado final continue perfeitamente normalizado.

In [35]:
import numpy as np

# 1. Definindo as Matrizes de Pauli e a Identidade no NumPy
I = np.array([[1 + 0j, 0 + 0j],
              [0 + 0j, 1 + 0j]])

X = np.array([[0 + 0j, 1 + 0j],
              [1 + 0j, 0 + 0j]])

Y = np.array([[0 + 0j, 0 - 1j],
              [0 + 1j, 0 + 0j]])

Z = np.array([[1 + 0j, 0 + 0j],
              [0 + 0j, -1 + 0j]])

print("Matriz de Pauli X (Bit-flip):")
print(X)

# 2. Aplicando a porta X no estado |0>
# Relembrando o Ket |0>
ket_0 = np.array([[1],
                  [0]])

# Multiplicação matriz-vetor usando np.dot()
ket_final = np.dot(X, ket_0)

print("\nAplicando a porta X no estado |0> (Resultado deve ser o Ket |1>):")
print(ket_final)

# 3. Verificando se a matriz Y é Unitária (Y_dagger * Y == I)
Y_dagger = Y.conj().T
produto_unitario = np.dot(Y_dagger, Y)

print("\n--- Verificação de Unitaridade (Y^† * Y) ---")
print(produto_unitario)

# Testando se o produto é numericamente igual à Matriz Identidade
if np.allclose(produto_unitario, I):
    print("\nSucesso: O produto resultou na identidade!")
    print("Conclusão: A matriz Y é perfeitamente UNITÁRIA.")
else:
    print("\nA matriz não é unitária.")

Matriz de Pauli X (Bit-flip):
[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]

Aplicando a porta X no estado |0> (Resultado deve ser o Ket |1>):
[[0.+0.j]
 [1.+0.j]]

--- Verificação de Unitaridade (Y^† * Y) ---
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]

Sucesso: O produto resultou na identidade!
Conclusão: A matriz Y é perfeitamente UNITÁRIA.


### 5. Produto Tensor e Espaços Compostos

Para construir computadores quânticos capazes de realizar cálculos complexos, um único *qubit* não é suficiente. Precisamos combinar múltiplos *qubits* para formar registradores quânticos maiores. A operação matemática que nos permite fundir dois ou mais espaços vetoriais independentes em um único sistema composto é o **Produto Tensor**, representado pelo símbolo $\otimes$.

De acordo com o **Postulado 4**, o espaço de estados de um sistema físico composto é o produto tensor dos espaços de estados dos sistemas que o compõem.

#### A. Produto Tensor de Vetores (Estados Compostos)
Se temos dois qubits isolados, um preparado no estado $|\psi\rangle$ e outro no estado $|\phi\rangle$, o estado conjunto do sistema de dois qubits é dado por:

$$|\Psi\rangle = |\psi\rangle \otimes |\phi\rangle$$

Matricialmente, o produto tensor (frequentemente chamado de produto de Kronecker na computação) funciona multiplicando cada elemento do primeiro vetor por todo o segundo vetor, gerando uma matriz coluna maior ($4 \times 1$):

$$|\Psi\rangle = \begin{bmatrix} a \\ b \end{bmatrix} \otimes \begin{bmatrix} c \\ d \end{bmatrix} = \begin{bmatrix} a \cdot \begin{bmatrix} c \\ d \end{bmatrix} \\ b \cdot \begin{bmatrix} c \\ d \end{bmatrix} \end{bmatrix} = \begin{bmatrix} ac \\ ad \\ bc \\ bd \end{bmatrix}$$

#### B. Crescimento Exponencial
Cada vez que adicionamos um novo *qubit* ao sistema através do produto tensor, a dimensão do nosso espaço vetorial **dobra**:
* 1 Qubit: dimensão $2^1 = 2$
* 2 Qubits: dimensão $2^2 = 4$
* 3 Qubits: dimensão $2^3 = 8$
* $n$ Qubits: dimensão $2^n$

Esse crescimento exponencial da capacidade de processamento de estados em paralelo é um dos pilares do poder da computação quântica.

In [36]:
import numpy as np

# Definindo os kets fundamentais de 1 qubit
ket_0 = np.array([[1],
                  [0]])

ket_1 = np.array([[0],
                  [1]])

print("--- 1. Criação de Estados Compostos de 2 Qubits ---")

# A função np.kron realiza o Produto de Kronecker (Produto Tensor no NumPy)
ket_00 = np.kron(ket_0, ket_0)
ket_11 = np.kron(ket_1, ket_1)

print("Estado composto |00> (dimensão 4x1):")
print(ket_00)

print("\nEstado composto |11> (dimensão 4x1):")
print(ket_11)

print("\n--- 2. Construindo um Estado de Bell (Emaranhamento Máximo) ---")
# Utilizando a fórmula baseada no Postulado 4: (|00> + |11>) / sqrt(2)
estado_bell = (ket_00 + ket_11) / np.sqrt(2)

print("Estado de Bell resultante |β_00>:")
print(estado_bell)

# Verificando a norma do estado composto (deve continuar sendo igual a 1)
norma_bell = np.linalg.norm(estado_bell)
print(f"\nNorma do Estado de Bell: {norma_bell}")

--- 1. Criação de Estados Compostos de 2 Qubits ---
Estado composto |00> (dimensão 4x1):
[[1]
 [0]
 [0]
 [0]]

Estado composto |11> (dimensão 4x1):
[[0]
 [0]
 [0]
 [1]]

--- 2. Construindo um Estado de Bell (Emaranhamento Máximo) ---
Estado de Bell resultante |β_00>:
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

Norma do Estado de Bell: 0.9999999999999999
